[build-system]
requires = [
"flit_core >=3.11,<4",
"build",
"keyboard",
"picamera"
]
build-backend = "flit_core.buildapi"

[project]
name = "pidashcam"
authors = [{name = "Gareth Howell", email = "gareth.howell@gmail.com"}]
readme = "README.rst"
license = "MIT"
license-files = ["LICENSE"]
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/garethhowell/pidashcam"
