#! /usr/bin/python -u

import pidashcam
import logging

# Initialise logging
logging.basicConfig(level = {'info':logging.INFO, 'debug':logging.DEBUG}[args.log_level])
log = logging.getLogger("pidashcam")
log.setLevel({'info':logging.INFO, 'debug':logging.DEBUG}[args.log_level])
log.info("piDashCam started")
log.debug(args)


dashcam = pidashcam.PiDashCam()
log.debug("dashcam = " + str(dashcam))
dashcam.run()
